### ISSUE TITLE
Null Pointer Exception

### ISSUE THREAD

**Issue by louisgv** [jammehcow/jenkins-discord#19]
For some reason it's failing for me. Here's the stack trace:
```
Archiving artifacts
ERROR: Buuild step failed with exception
java.lang.NullPointerException
	at nz.co.jammehcow.jenkinsdiscord.util.EmbedDescription.<init>(EmbedDescription.java:35)
	at nz.co.jammehcow.jenkinsdiscord.WebhookPublisher.perform(WebhookPublisher.java:99)
	at hudson.tasks.BuildStepMonitor$1.perform(BuildStepMonitor.java:20)
	at hudson.model.AbstractBuild$AbstractBuildExecution.perform(AbstractBuild.java:744)
	at hudson.model.AbstractBuild$AbstractBuildExecution.performAllBuildSteps(AbstractBuild.java:690)
	at hudson.model.Build$BuildExecution.cleanUp(Build.java:196)
	at hudson.model.Run.execute(Run.java:1774)
	at hudson.model.FreeStyleBuild.run(FreeStyleBuild.java:43)
	at hudson.model.ResourceController.execute(ResourceController.java:97)
	at hudson.model.Executor.run(Executor.java:429)
Build step 'Discord Notifier' marked build as failure
Finished: SUCCESS
```

**Comment by fuzzmz** [comment]
Also ran into this issue, running version 1.2 of the plugin. Will try and see if I'm able to reproduce it, as right now it's a one off occurrence.

**Comment by jupjohn** [comment]
We're you guys using SVN or another CVS system?

**Comment by fuzzmz** [comment]
In my case it was a job using both git and TFVC/TFS.

**Comment by jupjohn** [comment]
I'm unable to reproduce this (hence the label) so I'll add some better checks for methods on that line and that's as far as I can go. If you find a way to reproduce it, reopen this thread and I'll do my best to resolve it.

**Comment by jkage198** [comment]
Same issue, only it magically worked twice (after I disabled every check mark) and then no more. Usage: Jenkins/P4.

**Comment by jkage198** [comment]
@jammehcow After some tries I can confirm it works only when there are no changes from P4 to the current build. In the case where there is at least one change the exception is thrown.
