### ISSUE TITLE
NullPointerException

### ISSUE THREAD

**Issue by lodi-g** [jammehcow/jenkins-discord#2]
Hi,

It seems like I can't get jenkins-discord to work, at all. I built the .hpi file using `mvn package`, uploaded it to Jenkins and set up the Post built actions as described (http://i.imgur.com/aTlv5Dx.png).
However, when I schedule a build, it seems like jenkins-discord can't send the notification: when the build is finished and Jenkins starts processing the Post-Build actions, Java throws a NullPointerException:
```
ERROR: Build step failed with exception
java.lang.NullPointerException
	at nz.co.jammehcow.jenkinsdiscord.WebhookPublisher.perform(WebhookPublisher.java:42)
	at hudson.tasks.BuildStepMonitor$1.perform(BuildStepMonitor.java:20)
	at hudson.model.AbstractBuild$AbstractBuildExecution.perform(AbstractBuild.java:735)
	at hudson.model.AbstractBuild$AbstractBuildExecution.performAllBuildSteps(AbstractBuild.java:676)
	at hudson.model.Build$BuildExecution.cleanUp(Build.java:196)
	at hudson.model.Run.execute(Run.java:1782)
	at hudson.model.FreeStyleBuild.run(FreeStyleBuild.java:43)
	at hudson.model.ResourceController.execute(ResourceController.java:97)
	at hudson.model.Executor.run(Executor.java:405)
Build step 'Discord Notifier' marked build as failure
Finished: SUCCESS
```

How should I fix that?

Thanks!

**Comment by jupjohn** [comment]
I'm a bit busy at the moment but I have a rough idea what it might be. Is your Jenkins URL in your global config set?

EDIT: As far as I know `e40a69` fixes this issue. Leaving this issue open if I'm wrong.

**Comment by lodi-g** [comment]
With your latest commit there is no more NullPtrException, however the plugin notifies me about 'Your Jenkins URL is not set (or is set to localhost)!' although it is correctly set imho: http://i.imgur.com/Y09ws6o.png

Thanks again.

**Comment by jupjohn** [comment]
I would try removing the URL from the field, saving it, then putting it back in. It must be returning null for the URL which should only happen if it's the loopback IP. Try a quick restart and if nothing works return back.

**Comment by lodi-g** [comment]
I removed the URL, saved, built, saved again, built, and now it seems to be working. Thank you for the support. Closing this!

**Comment by jupjohn** [comment]
Weird. Might put in a feature to fix that if it's a prominent issue.

Enjoy.

**Comment by andyczerwonka** [comment]
Hmnnnn... I wonder it this is related to my issue? I can't get it to work at all either. See #6

**Comment by melt7777** [comment]
Hello, melt7777 here.
We keep getting this in our console output: I do not know what else to provide you for troubleshooting. I see this should have been fixed long ago. After this error, nothing is posted to the discord. It happens intermittently (the worst case to troubleshoot!) 

```
ERROR: Build step failed with exception
java.lang.NullPointerException
	at nz.co.jammehcow.jenkinsdiscord.WebhookPublisher.perform(WebhookPublisher.java:102)
	at hudson.tasks.BuildStepMonitor$1.perform(BuildStepMonitor.java:20)
	at hudson.model.AbstractBuild$AbstractBuildExecution.perform(AbstractBuild.java:744)
	at hudson.model.AbstractBuild$AbstractBuildExecution.performAllBuildSteps(AbstractBuild.java:690)
	at hudson.model.Build$BuildExecution.cleanUp(Build.java:196)
	at hudson.model.Run.execute(Run.java:1866)
	at hudson.model.FreeStyleBuild.run(FreeStyleBuild.java:43)
	at hudson.model.ResourceController.execute(ResourceController.java:97)
	at hudson.model.Executor.run(Executor.java:429)
Build step 'Discord Notifier' marked build as failure
Finished: SUCCESS
```
We are using latest jenkins, and the latest Release version of the Discord Notifier "v1.4.1 - Enum result
@KocproZ KocproZ released this 5 days ago · 4 commits to master since this release"
Also, we do have the URL set properly in Jenkins settings. Any advice?
