### ISSUE TITLE
Upgrade to 1.3.0 - error when compiling

### ISSUE THREAD

**Issue by mTrax-** [jammehcow/jenkins-discord#31]
Hi,

After upgrading to 1.3.0, I have this error when compiling.
Any clue ?

Cheers,
G.

```
Java.lang.NullPointerException
	at nz.co.jammehcow.jenkinsdiscord.WebhookPublisher.perform(WebhookPublisher.java:94)
	at hudson.tasks.BuildStepMonitor$1.perform(BuildStepMonitor.java:20)
	at hudson.model.AbstractBuild$AbstractBuildExecution.perform(AbstractBuild.java:744)
	at hudson.model.AbstractBuild$AbstractBuildExecution.performAllBuildSteps(AbstractBuild.java:690)
	at hudson.model.Build$BuildExecution.cleanUp(Build.java:196)
	at hudson.model.Run.execute(Run.java:1862)
	at hudson.model.FreeStyleBuild.run(FreeStyleBuild.java:43)
	at hudson.model.ResourceController.execute(ResourceController.java:97)
	at hudson.model.Executor.run(Executor.java:429)
Build step 'Discord Notifier' marked build as failure
```

**Comment by KocproZ** [comment]
I couldn't reproduce this issue.
Can you go into webhook configuraton and set/change the Title and then try again?

**Comment by aveao** [comment]
Can repro, testing with title.

**Comment by aveao** [comment]
Works, but why is this a problem that's happening now and why didn't it happen before? It should really be fixed.

**Comment by KocproZ** [comment]
When adding functionality to this plugin new variables were added to [WebhookPublisher](https://github.com/jammehcow/jenkins-discord/blob/master/src/main/java/nz/co/jammehcow/jenkinsdiscord/WebhookPublisher.java). While they are set in a constructor, Jenkins calls the constructor only when changes to project's configuration are made. It means that when plugin is updated, but project's configuration isn't changed, the new variables are null when they shouldn't.

Changing the project configuration is a workaround, because it forces Jenkins to call the WebhookPublisher constructor.

**Comment by aveao** [comment]
Wouldn't it make sense to have default values so that the plugin doesn't die when values are inputted as null?
