### ISSUE TITLE
NRE when no footer is given

### ISSUE THREAD

**Issue by Alloc86** [jammehcow/jenkins-discord#38]
Hi,

first of all: Great plugin! Easy to use and exactly what I needed :)

Just stumbled on a minor issue: When using this plugin as a pipeline step and leaving out the "footer" parameter you get a NRE:
`java.lang.NullPointerException
	at nz.co.jammehcow.jenkinsdiscord.DiscordPipelineStep$DiscordPipelineStepExecution.checkLimitAndTruncate(DiscordPipelineStep.java:143)
	at nz.co.jammehcow.jenkinsdiscord.DiscordPipelineStep$DiscordPipelineStepExecution.run(DiscordPipelineStep.java:133)
	at nz.co.jammehcow.jenkinsdiscord.DiscordPipelineStep$DiscordPipelineStepExecution.run(DiscordPipelineStep.java:111)
	at org.jenkinsci.plugins.workflow.steps.AbstractSynchronousNonBlockingStepExecution$1$1.call(AbstractSynchronousNonBlockingStepExecution.java:47)
	at hudson.security.ACL.impersonate(ACL.java:290)
	at org.jenkinsci.plugins.workflow.steps.AbstractSynchronousNonBlockingStepExecution$1.run(AbstractSynchronousNonBlockingStepExecution.java:44)
	at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source)
	at java.util.concurrent.FutureTask.run(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.lang.Thread.run(Unknown Source)`

Can easily be worked around by supplying an empty string, but it would obviously be nice if the plugin didn't freak out if you just omit it :)

Regards,
Chris

**Comment by KocproZ** [comment]
Hi,
Thanks for the report, I'm glad you like the plugin.
I bundled the fix with some other changes and will release it soon.
