### ISSUE TITLE
Cannot build latest 1.4.1 on windows Eclipse

### ISSUE THREAD

**Issue by melt7777** [jammehcow/jenkins-discord#40]
Hey guys, new to Maven but I was following my notes from when I built v1.1.0 successfully and followed the same steps. Apparently this build is failing the test part of the compile but I do not know how to troubleshoot further. Any help would be greatly appreciated. 

The steps that I followed are found here under "Manual Installation using Eclipse for Windows" (You might remember I asked to have this documentation included here as a pull request, but was snubbed.)
https://github.com/melt7777/jenkins-discord/blob/master/README.md

Here is the console output from Eclipse:

```
[INFO] Scanning for projects...
[WARNING] The POM for org.jenkins-ci.tools:maven-hpi-plugin:jar:1.117 is missing, no dependency information available
[WARNING] Failed to build parent project for nz.co.jammehcow:discord-notifier:hpi:1.4.1
[INFO] 
[INFO] ------------------< nz.co.jammehcow:discord-notifier >------------------
[INFO] Building Discord Notifier 1.4.1
[INFO] --------------------------------[ hpi ]---------------------------------
[INFO] 
[INFO] --- maven-hpi-plugin:1.117:validate (default-validate) @ discord-notifier ---
[INFO] 
[INFO] --- maven-enforcer-plugin:1.3.1:display-info (display-info) @ discord-notifier ---
[INFO] Maven Version: 3.5.3
[INFO] JDK Version: 1.8.0_181 normalized as: 1.8.0-181
[INFO] OS Info: Arch: amd64 Family: dos Name: windows 10 Version: 10.0
[INFO] 
[INFO] --- maven-enforcer-plugin:1.3.1:enforce (display-info) @ discord-notifier ---
[INFO] 
[INFO] --- maven-localizer-plugin:1.23:generate (default) @ discord-notifier ---
[INFO] 
[INFO] >>> maven-javadoc-plugin:2.10.1:javadoc (default) > generate-sources @ discord-notifier >>>
[INFO] 
[INFO] --- maven-hpi-plugin:1.117:validate (default-validate) @ discord-notifier ---
[INFO] 
[INFO] --- maven-enforcer-plugin:1.3.1:display-info (display-info) @ discord-notifier ---
[INFO] Maven Version: 3.5.3
[INFO] JDK Version: 1.8.0_181 normalized as: 1.8.0-181
[INFO] OS Info: Arch: amd64 Family: dos Name: windows 10 Version: 10.0
[INFO] 
[INFO] --- maven-enforcer-plugin:1.3.1:enforce (display-info) @ discord-notifier ---
[INFO] 
[INFO] --- maven-localizer-plugin:1.23:generate (default) @ discord-notifier ---
[INFO] 
[INFO] <<< maven-javadoc-plugin:2.10.1:javadoc (default) < generate-sources @ discord-notifier <<<
[INFO] 
[INFO] 
[INFO] --- maven-javadoc-plugin:2.10.1:javadoc (default) @ discord-notifier ---
[INFO] 
Loading source files for package nz.co.jammehcow.jenkinsdiscord...
Loading source files for package nz.co.jammehcow.jenkinsdiscord.exception...
Loading source files for package nz.co.jammehcow.jenkinsdiscord.util...
Constructing Javadoc information...
Standard Doclet version 1.8.0_181
Building tree for all the packages and classes...
Generating C:\Users\melt\git\jenkins-discord-1.4.1\target\site\apidocs\nz\co\jammehcow\jenkinsdiscord\DiscordPipelineStep.html...
Generating C:\Users\melt\git\jenkins-discord-1.4.1\target\site\apidocs\nz\co\jammehcow\jenkinsdiscord\DiscordPipelineStep.DescriptorImpl.html...
Generating C:\Users\melt\git\jenkins-discord-1.4.1\target\site\apidocs\nz\co\jammehcow\jenkinsdiscord\DiscordPipelineStep.DiscordPipelineStepExecution.html...
Generating C:\Users\melt\git\jenkins-discord-1.4.1\target\site\apidocs\nz\co\jammehcow\jenkinsdiscord\WebhookPublisher.html...
Generating C:\Users\melt\git\jenkins-discord-1.4.1\target\site\apidocs\nz\co\jammehcow\jenkinsdiscord\WebhookPublisher.DescriptorImpl.html...
Generating C:\Users\melt\git\jenkins-discord-1.4.1\target\site\apidocs\nz\co\jammehcow\jenkinsdiscord\exception\WebhookException.html...
Generating C:\Users\melt\git\jenkins-discord-1.4.1\target\site\apidocs\nz\co\jammehcow\jenkinsdiscord\util\EmbedDescription.html...
Generating C:\Users\melt\git\jenkins-discord-1.4.1\target\site\apidocs\overview-frame.html...
Generating C:\Users\melt\git\jenkins-discord-1.4.1\target\site\apidocs\nz\co\jammehcow\jenkinsdiscord\package-frame.html...
Generating C:\Users\melt\git\jenkins-discord-1.4.1\target\site\apidocs\nz\co\jammehcow\jenkinsdiscord\package-summary.html...
Generating C:\Users\melt\git\jenkins-discord-1.4.1\target\site\apidocs\nz\co\jammehcow\jenkinsdiscord\package-tree.html...
Generating C:\Users\melt\git\jenkins-discord-1.4.1\target\site\apidocs\nz\co\jammehcow\jenkinsdiscord\exception\package-frame.html...
Generating C:\Users\melt\git\jenkins-discord-1.4.1\target\site\apidocs\nz\co\jammehcow\jenkinsdiscord\exception\package-summary.html...
Generating C:\Users\melt\git\jenkins-discord-1.4.1\target\site\apidocs\nz\co\jammehcow\jenkinsdiscord\exception\package-tree.html...
Generating C:\Users\melt\git\jenkins-discord-1.4.1\target\site\apidocs\nz\co\jammehcow\jenkinsdiscord\util\package-frame.html...
Generating C:\Users\melt\git\jenkins-discord-1.4.1\target\site\apidocs\nz\co\jammehcow\jenkinsdiscord\util\package-summary.html...
Generating C:\Users\melt\git\jenkins-discord-1.4.1\target\site\apidocs\nz\co\jammehcow\jenkinsdiscord\util\package-tree.html...
Generating C:\Users\melt\git\jenkins-discord-1.4.1\target\site\apidocs\constant-values.html...
Generating C:\Users\melt\git\jenkins-discord-1.4.1\target\site\apidocs\serialized-form.html...
Generating C:\Users\melt\git\jenkins-discord-1.4.1\target\site\apidocs\nz\co\jammehcow\jenkinsdiscord\class-use\WebhookPublisher.html...
Generating C:\Users\melt\git\jenkins-discord-1.4.1\target\site\apidocs\nz\co\jammehcow\jenkinsdiscord\class-use\WebhookPublisher.DescriptorImpl.html...
Generating C:\Users\melt\git\jenkins-discord-1.4.1\target\site\apidocs\nz\co\jammehcow\jenkinsdiscord\class-use\DiscordPipelineStep.html...
Generating C:\Users\melt\git\jenkins-discord-1.4.1\target\site\apidocs\nz\co\jammehcow\jenkinsdiscord\class-use\DiscordPipelineStep.DiscordPipelineStepExecution.html...
Generating C:\Users\melt\git\jenkins-discord-1.4.1\target\site\apidocs\nz\co\jammehcow\jenkinsdiscord\class-use\DiscordPipelineStep.DescriptorImpl.html...
Generating C:\Users\melt\git\jenkins-discord-1.4.1\target\site\apidocs\nz\co\jammehcow\jenkinsdiscord\exception\class-use\WebhookException.html...
Generating C:\Users\melt\git\jenkins-discord-1.4.1\target\site\apidocs\nz\co\jammehcow\jenkinsdiscord\util\class-use\EmbedDescription.html...
Generating C:\Users\melt\git\jenkins-discord-1.4.1\target\site\apidocs\nz\co\jammehcow\jenkinsdiscord\package-use.html...
Generating C:\Users\melt\git\jenkins-discord-1.4.1\target\site\apidocs\nz\co\jammehcow\jenkinsdiscord\exception\package-use.html...
Generating C:\Users\melt\git\jenkins-discord-1.4.1\target\site\apidocs\nz\co\jammehcow\jenkinsdiscord\util\package-use.html...
Building index for all the packages and classes...
Generating C:\Users\melt\git\jenkins-discord-1.4.1\target\site\apidocs\overview-tree.html...
Generating C:\Users\melt\git\jenkins-discord-1.4.1\target\site\apidocs\index-all.html...
Generating C:\Users\melt\git\jenkins-discord-1.4.1\target\site\apidocs\deprecated-list.html...
Building index for all classes...
Generating C:\Users\melt\git\jenkins-discord-1.4.1\target\site\apidocs\allclasses-frame.html...
Generating C:\Users\melt\git\jenkins-discord-1.4.1\target\site\apidocs\allclasses-noframe.html...
Generating C:\Users\melt\git\jenkins-discord-1.4.1\target\site\apidocs\index.html...
Generating C:\Users\melt\git\jenkins-discord-1.4.1\target\site\apidocs\overview-summary.html...
Generating C:\Users\melt\git\jenkins-discord-1.4.1\target\site\apidocs\help-doc.html...
[INFO] 
[INFO] --- maven-resources-plugin:2.7:resources (default-resources) @ discord-notifier ---
[INFO] Using 'UTF-8' encoding to copy filtered resources.
[INFO] Copying 20 resources
[INFO] 
[INFO] --- maven-compiler-plugin:3.3:compile (default-compile) @ discord-notifier ---
[INFO] Changes detected - recompiling the module!
[INFO] Compiling 5 source files to C:\Users\melt\git\jenkins-discord-1.4.1\target\classes
[INFO] /C:/Users/melt/git/jenkins-discord-1.4.1/src/main/java/nz/co/jammehcow/jenkinsdiscord/util/EmbedDescription.java: C:\Users\melt\git\jenkins-discord-1.4.1\src\main\java\nz\co\jammehcow\jenkinsdiscord\util\EmbedDescription.java uses unchecked or unsafe operations.
[INFO] /C:/Users/melt/git/jenkins-discord-1.4.1/src/main/java/nz/co/jammehcow/jenkinsdiscord/util/EmbedDescription.java: Recompile with -Xlint:unchecked for details.
[INFO] 
[INFO] --- access-modifier-checker:1.7:enforce (default-enforce) @ discord-notifier ---
[INFO] 
[INFO] --- animal-sniffer-maven-plugin:1.14:check (check) @ discord-notifier ---
[INFO] Resolved signature org.codehaus.mojo.signature:java17 version as 1.0 from dependencyManagement
[INFO] Checking unresolved references to org.codehaus.mojo.signature:java17:1.0
[INFO] 
[INFO] --- maven-hpi-plugin:1.117:insert-test (default-insert-test) @ discord-notifier ---
[INFO] 
[INFO] --- gmaven-plugin:1.5-jenkins-3:generateTestStubs (test-in-groovy) @ discord-notifier ---
[INFO] No sources found for Java stub generation
[INFO] 
[INFO] --- maven-resources-plugin:2.7:testResources (default-testResources) @ discord-notifier ---
[INFO] Using 'UTF-8' encoding to copy filtered resources.
[INFO] skip non existing resourceDirectory C:\Users\melt\git\jenkins-discord-1.4.1\src\test\resources
[INFO] 
[INFO] --- maven-compiler-plugin:3.3:testCompile (default-testCompile) @ discord-notifier ---
[INFO] Changes detected - recompiling the module!
[INFO] Compiling 1 source file to C:\Users\melt\git\jenkins-discord-1.4.1\target\test-classes
[INFO] /C:/Users/melt/git/jenkins-discord-1.4.1/target/generated-test-sources/injected/InjectedTest.java: C:\Users\melt\git\jenkins-discord-1.4.1\target\generated-test-sources\injected\InjectedTest.java uses unchecked or unsafe operations.
[INFO] /C:/Users/melt/git/jenkins-discord-1.4.1/target/generated-test-sources/injected/InjectedTest.java: Recompile with -Xlint:unchecked for details.
[INFO] 
[INFO] --- maven-hpi-plugin:1.117:test-hpl (default-test-hpl) @ discord-notifier ---
[INFO] Generating C:\Users\melt\git\jenkins-discord-1.4.1\target\test-classes\the.hpl
[INFO] 
[INFO] --- maven-hpi-plugin:1.117:resolve-test-dependencies (default-resolve-test-dependencies) @ discord-notifier ---
[INFO] 
[INFO] --- gmaven-plugin:1.5-jenkins-3:testCompile (test-in-groovy) @ discord-notifier ---
[INFO] No sources found to compile
[INFO] 
[INFO] --- maven-surefire-plugin:2.19.1:test (default-test) @ discord-notifier ---

-------------------------------------------------------
 T E S T S
-------------------------------------------------------
Running InjectedTest
Tests run: 9, Failures: 0, Errors: 5, Skipped: 0, Time elapsed: 38.378 sec <<< FAILURE! - in InjectedTest
nz\co\jammehcow\jenkinsdiscord\DiscordPipelineStep\config.jelly(org.jvnet.hudson.test.JellyTestSuiteBuilder$JellyCheck)  Time elapsed: 0.055 sec  <<< ERROR!
org.apache.commons.jelly.JellyException: Could not parse Jelly script : file:/C:/Users/melt/git/jenkins-discord-1.4.1/target/classes/nz/co/jammehcow/jenkinsdiscord/DiscordPipelineStep/config.jelly
	at org.jvnet.hudson.test.JellyTestSuiteBuilder$JellyCheck.runTest(JellyTestSuiteBuilder.java:102)
Caused by: org.xml.sax.SAXParseException: The element type "f:textbox" must be terminated by the matching end-tag "</f:textbox>".
	at org.jvnet.hudson.test.JellyTestSuiteBuilder$JellyCheck.runTest(JellyTestSuiteBuilder.java:102)

initializationError(org.junit.runner.manipulation.Filter)  Time elapsed: 0 sec  <<< ERROR!
java.lang.Exception: No tests found matching Method nz\co\jammehcow\jenkinsdiscord\DiscordPipelineStep\config.jelly(org.jvnet.hudson.test.JellyTestSuiteBuilder$JellyCheck) from org.junit.internal.requests.ClassRequest@d13baac

initializationError(org.junit.runner.manipulation.Filter)  Time elapsed: 0 sec  <<< ERROR!
java.lang.Exception: No runnable methods

initializationError(org.junit.runner.manipulation.Filter)  Time elapsed: 0 sec  <<< ERROR!
java.lang.Exception: No runnable methods

initializationError(org.junit.runner.manipulation.Filter)  Time elapsed: 0 sec  <<< ERROR!
java.lang.Exception: No runnable methods


Results :

Tests in error: 
org.junit.runner.manipulation.Filter.initializationError(org.junit.runner.manipulation.Filter)
  Run 1: Filter.initializationError »  No tests found matching Method nz\co\jammehcow\j...
  Run 2: Filter.initializationError »  No runnable methods
  Run 3: Filter.initializationError »  No runnable methods
  Run 4: Filter.initializationError »  No runnable methods

  JellyTestSuiteBuilder$JellyCheck.runTest:102 » Jelly Could not parse Jelly scr...

Tests run: 6, Failures: 0, Errors: 2, Skipped: 0

[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 55.508 s
[INFO] Finished at: 2018-11-02T10:52:08-04:00
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal org.apache.maven.plugins:maven-surefire-plugin:2.19.1:test (default-test) on project discord-notifier: There are test failures.
[ERROR] 
[ERROR] Please refer to C:\Users\melt\git\jenkins-discord-1.4.1\target\surefire-reports for the individual test results.
[ERROR] -> [Help 1]
[ERROR] 
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR] 
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/MojoFailureException

```

Many thanks in advance, 
melt
getpimp.org | miner.farm

**Comment by KocproZ** [comment]
Hey,
Build was failing because of a single `/` missing in one of the files., fix is already pushed.
I just want to add that you don't have to build it yourself as you can acquire hpi file [here](https://github.com/KocproZ/jenkins-discord/releases/tag/v1.4.1).

**Comment by melt7777** [comment]
Thanks very much for that, the hpi saves me a ton of trouble, but glad that I was doing it right. Also, the new features such as being able to specify Title, branch name, and URL are top notch. I was about to request such a feature but you already did it - Many many thanks!

~ melt
getpimp.org | miner.farm
