### ISSUE TITLE
NullPointerException issue, similar to previous reported one

### ISSUE THREAD

**Issue by melt7777** [jammehcow/jenkins-discord#42]
We keep getting this in our console output: I do not know what else to provide you for troubleshooting. I see this should have been fixed long ago. After this error, nothing is posted to the discord. It happens intermittently (the worst case to troubleshoot!) 

```
ERROR: Build step failed with exception
java.lang.NullPointerException
	at nz.co.jammehcow.jenkinsdiscord.WebhookPublisher.perform(WebhookPublisher.java:102)
	at hudson.tasks.BuildStepMonitor$1.perform(BuildStepMonitor.java:20)
	at hudson.model.AbstractBuild$AbstractBuildExecution.perform(AbstractBuild.java:744)
	at hudson.model.AbstractBuild$AbstractBuildExecution.performAllBuildSteps(AbstractBuild.java:690)
	at hudson.model.Build$BuildExecution.cleanUp(Build.java:196)
	at hudson.model.Run.execute(Run.java:1866)
	at hudson.model.FreeStyleBuild.run(FreeStyleBuild.java:43)
	at hudson.model.ResourceController.execute(ResourceController.java:97)
	at hudson.model.Executor.run(Executor.java:429)
Build step 'Discord Notifier' marked build as failure
Finished: SUCCESS
```
We are using latest jenkins, and the latest Release version of the Discord Notifier "v1.4.1 - Enum result
@KocproZ KocproZ released this 5 days ago · 4 commits to master since this release"
Also, we do have the URL set properly in Jenkins settings. Any advice?

_Originally posted by @melt7777 in https://github.com/KocproZ/jenkins-discord/issue_comments#issuecomment-436748773_

**Comment by KocproZ** [comment]
Hi,
Can you tell me what is the `Title` value in your discord notify step configuration?
Also, can you change it and try again?

**Comment by melt7777** [comment]
hello, the Title was blank (empty). I changed it to `repo-pimp-miners-tgz` and it now works as designed. I would say, the issue can be closed as resolved, as there is a valid solution, but am happy to test further if you would like. Thanks again!!
